# Generated by Django 3.2.6 on 2021-08-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
